behaviors:
  ShipBrain:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 2048
    beta: 5.0e-4
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
