behaviors:
  ShipBrain:
    trainer_type: ppo
    max_steps: 1000000
    time_horizon: 256
    summary_freq: 10000
    keep_checkpoints: 5
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
